# We deliberately don't use travis's language=python option because
# we install miniconda and use conda to get python. Additionally, 
# Travis's auto-install of python doesn't work on osx images (see
# https://github.com/travis-ci/travis-ci/issues/4729).
language: generic

stages:
  - test
    if: (branch != pkg)
  - doc
    if: (branch != pkg)
  - name: conda_dev_package
    if: (branch = pkg)

jobs:
  include:
    - &default
      stage: test
      os: linux
      env:
        - PYTHON_VERSION="3.6"
      install:
        # Install conda
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
          else
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
          fi
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda config --set always_yes yes --set changeps1 no
        - conda update conda
        # it might be faster to start from anaconda instead of miniconda
        - travis_wait 20 conda env create --file environment.yml python=$PYTHON_VERSION
        - source activate pyviz
        # dependencies for tests etc
        - pip install flake8
        - conda env export
        - conda list
      script:
          - python download_sample_data.py
          # python ./etc/test_notebooks.py lint
          - python ./etc/test_notebooks.py

    - <<: *default
      os: osx
      before_install:
        # brew-installed geos interferes with cartopy?
        - brew uninstall --ignore-dependencies geos gdal postgis
      if: branch = master AND type != pull_request
      deploy: true

    - <<: *default
      stage: doc
      script:
        - python download_sample_data.py     
        - conda install -c conda-forge 'sphinx<1.7' beautifulsoup4 graphviz
        - pip install nbsite
        - pip install sphinx_ioam_theme
        - cd doc/tutorial
        - nbsite_nbpagebuild.py pyviz pyviz ../../notebooks . 1
        - cd ..
        - sphinx-build -b html . ./_build/html
        - nbsite_fix_links.py _build/html
        - cp -r ../notebooks/assets _build/html/tutorial/
        - touch ./_build/html/.nojekyll
        - nbsite_cleandisthtml.py ./_build/html take_a_chance
        - cd ..
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: ./doc/_build/html
        on:
          tags: true


    - stage: conda_dev_package
      os: linux
      env:
        - PYTHON_VERSION="3.6"
      before_install:
        ## use system python to install doit, then use doit to install miniconda
        - easy_install --user doit==0.29.0 pyct && ~/.local/bin/doit install_miniconda && rm -f .doit.db
        - export PATH="$HOME/miniconda/bin:$PATH"
        ## install doit into miniconda
        - conda install -y -c pyviz/label/dev -c conda-forge pyct
        - doit ci_configure_conda

      install:
        - export VERSIONHACK=$(python -c "import subprocess;desc=subprocess.check_output(['git','describe','--long']).decode('utf8');v,commits=desc.split('-')[0:2];newv=[int(x) for x in v.split('.')];newv[-1]+=1;print('.'.join(str(x) for x in newv)+'.dev'+commits)")      
        - doit build_conda_package --channel=pyviz/label/dev --channel=bokeh --channel=conda-forge
      script: true
#        - doit upload_conda_package --token=$CONDA_UPLOAD_TOKEN


notifications:
  email: false
