name: pyviz
channels:
  - pyviz/label/dev
  - defaults
dependencies:
  - bokeh >=1.2.0
  - holoviews >=1.12.3
  - hvplot >=0.4.0
  - datashader >=0.7.0
  - panel >=0.6.0
  - param >=1.9.1
  - pyct[cmd] >=0.4.6
  - ipython >=5.4.0,<=7.1.1
  - numpy >=1.16.4
  - rise
  - dask[complete] >=0.18.2
  # Pinned to avoid rate limiting for large images with notebook=5.0
  - notebook >=5.5
  # Pinned to avoid warnings until holoviews 1.12.4 is released
  - matplotlib ==3.0.3
  - pandas >=0.23.4,<0.25.0
  - xarray >=0.11.0,<0.12
  - streamz
  # for reading .nc files
  - netcdf4
  # for reading Parquet files (minimum version required by pandas 0.24)
  - fastparquet>=0.2.1
  # for exporting Bokeh plots to PNG
  - selenium
  # inadvertent dependency of streamz
  - ipywidgets
  # graphs
  - networkx
  - scikit-image
  # geo
  - cartopy
  - geopandas
  - geoviews >=1.6.2
  # for exporting Bokeh plots to PNG
  - phantomjs
  # for reading snappy-compressed Parquet files
  - python-snappy
  # Unstated dependency of fastparquet?
  - cffi
  # so we can pin to 3.6
  - python
