name: docs

on:
  push:
    branches:
      - gh_actions
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+a[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+b[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  build_docs:
    name: Documentation
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
    timeout-minutes: 120
    defaults:
      run:
        shell: bash -l {0}
    env:
      DESC: "Documentation build"
      MPLBACKEND: "Agg"
      MOZ_HEADLESS: 1
      DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "100"
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow -f
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: conda setup
        run: |
          conda config --set always_yes True
          conda install -c pyviz "pyctdev>=0.5"
          doit ecosystem_setup
          doit env_create --python=3.7
      - name: doit develop_install
        run: |
          eval "$(conda shell.bash hook)"
          conda activate test-environment
          conda list
          conda install anaconda-project
          cd examples
          anaconda-project prepare
          conda activate envs/default
          conda install -c pyviz/label/dev nbsite
      - name: generate rst
        run: |
          eval "$(conda shell.bash hook)"
          cd examples
          conda activate envs/default
          nbsite generate-rst --org holoviz --project-name holoviz --offset 1
      - name: build docs
        run: |
          eval "$(conda shell.bash hook)"
          cd examples
          conda activate envs/default
          nbsite build --what=html --output=builtdocs
      - name: git status
        run: |
          git status
          git diff
      - name: Deploy dev
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: pyviz-dev/holoviz
          publish_dir: ./builtdocs
          force_orphan: true
